/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as NewsBeritaRouteImport } from './routes/_news/berita'
import { Route as NewsSlugSlugRouteImport } from './routes/_news/$slug/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsBeritaRoute = NewsBeritaRouteImport.update({
  id: '/_news/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugSlugRoute = NewsSlugSlugRouteImport.update({
  id: '/_news/$slug/$slug',
  path: '/$slug/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/berita': typeof NewsBeritaRoute
  '/$slug/$slug': typeof NewsSlugSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/berita': typeof NewsBeritaRoute
  '/$slug/$slug': typeof NewsSlugSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_news/berita': typeof NewsBeritaRoute
  '/_news/$slug/$slug': typeof NewsSlugSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/berita' | '/$slug/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/berita' | '/$slug/$slug'
  id: '__root__' | '/' | '/$' | '/_news/berita' | '/_news/$slug/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  NewsBeritaRoute: typeof NewsBeritaRoute
  NewsSlugSlugRoute: typeof NewsSlugSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_news/berita': {
      id: '/_news/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof NewsBeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_news/$slug/$slug': {
      id: '/_news/$slug/$slug'
      path: '/$slug/$slug'
      fullPath: '/$slug/$slug'
      preLoaderRoute: typeof NewsSlugSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  NewsBeritaRoute: NewsBeritaRoute,
  NewsSlugSlugRoute: NewsSlugSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
